# Generated by Django 5.1.1 on 2025-02-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
