# Generated by Django 5.1.1 on 2025-02-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
